### ISSUE TITLE
abbr[title]

### ISSUE THREAD

**Issue by vancivelik** [ivansglazunov/reset-css#7]
``` css
abbr[title] {
   border-bottom: 1px dotted black;
}
```

from [normalize.css](https://github.com/vancivelik/normalize.css/blob/master/normalize.css)
